## Módulo de limpieza de datasets de Fondos.

-> Los datasets leidos y limpiados en este módulo provienen del scraping de la siguiente página Web:
- [Morningstar](https://www.morningstar.es/es/)

A continuación, para la limpieza de datos seguiremos los siguientes pasos.
1. Lectura de datos y concatenación de dataframes.
2. Eliminado de filas duplicadas.
3. Tratamiento de celdas
---

In [117]:
import pandas as pd

### 1. Limpieza de datos y concatenación de dataframes.

In [ ]:
# Valores que significan nulos en los excel.
na_val = {'-', 'n/a'}

# Lectura de los excel y declaración de nulos como np.nan
df1 = pd.read_excel('../data/DatosFondos1.xlsx', na_values=na_val, index_col=0)
df2 = pd.read_excel('../data/DatosFondos3.xlsx', na_values=na_val, index_col=0)
df3 = pd.read_excel('../data/DatosFondos3.xlsx', na_values=na_val, index_col=0)

# Concatenamos los datasets.
df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

# Para ver el número de filas
df.tail()

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
275,Abante Índice Bolsa L FI,ES0165939002,"EUR 17,89","19,63","16,13","-13,83","25,39","3,56","24,63","-6,89",NaN,"0,50%","0,87%","12,36 %"
276,Abante Índice Selección A FI,ES0162949012,"EUR 13,15","11,45","9,48","-9,95","12,08","0,70","12,84","-5,12",NaN,"1,00%","1,32%","7,40 %"
277,Abante Índice Selección L FI,ES0162949004,"EUR 13,59","11,80","10,02","-9,50","12,59","1,15","13,28","-4,62",NaN,"0,50%","0,82%","7,40 %"
278,Abante Moderado A FI,ES0109655037,"EUR 16,50","8,46","8,05","-9,33","8,84","-2,10","6,84","-6,27","3,23","0,50%","1,12%","6,48 %"
279,Abante Patrimonio Global A FI,ES0105013033,"EUR 21,98","14,16","10,12","-13,36","19,69","-5,37","10,34","-9,81","5,50","1,00%","1,90%","10,55 %"

### 2. Eliminado de filas que no interesan.

- Eliminamos las filas cuyos ISIN se repiten (identificador)

In [119]:
df = df.drop_duplicates(subset=['ISIN'], keep='first') # Si 2 se repiten, conservamos el primero
df.head()

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
0,AB - Emerging Markets Low Volatility Equity Po...,LU1005412462,"USD 24,77","17,78","14,54","-17,63","5,33","6,83","18,08","-12,52","16,74","0,85%","1,15%","12,34 %"
1,AB - Select US Equity Portfolio S1 EUR Acc,LU1764069099,"EUR 81,85","35,24","15,49","-8,36","39,58","6,11","32,03",NaN,NaN,"0,75%","0,82%","13,53 %"
2,AB - Select US Equity Portfolio S1 USD Acc,LU0683601610,"USD 85,96","35,60","15,07","-8,20","39,98","5,96","31,68","-0,12","7,37","0,75%","0,82%","13,56 %"
3,AB - Select US Equity Portfolio W EUR Acc,LU1404935469,"EUR 47,17","35,44","15,70","-8,20","38,45","6,38","32,41","-0,54",NaN,"0,45%","0,65%","13,53 %"
4,AB - Select US Equity Portfolio W USD Acc,LU1404935386,"USD 49,59","35,80","15,28","-8,02","38,84","6,20","32,08","-0,17","7,10","0,45%","0,65%","13,56 %"

- Eliminamos filas que no tienen datos en Gastos Corrientes.

Esto lo hacemos porque sin ese dato no podemos calcular la rentabilidad neta, y inventarselo supondría **pérdida de fiabilidad**

In [120]:
df = df.dropna(subset=['Gastos Corrientes'])
df.head()

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
0,AB - Emerging Markets Low Volatility Equity Po...,LU1005412462,"USD 24,77","17,78","14,54","-17,63","5,33","6,83","18,08","-12,52","16,74","0,85%","1,15%","12,34 %"
1,AB - Select US Equity Portfolio S1 EUR Acc,LU1764069099,"EUR 81,85","35,24","15,49","-8,36","39,58","6,11","32,03",NaN,NaN,"0,75%","0,82%","13,53 %"
2,AB - Select US Equity Portfolio S1 USD Acc,LU0683601610,"USD 85,96","35,60","15,07","-8,20","39,98","5,96","31,68","-0,12","7,37","0,75%","0,82%","13,56 %"
3,AB - Select US Equity Portfolio W EUR Acc,LU1404935469,"EUR 47,17","35,44","15,70","-8,20","38,45","6,38","32,41","-0,54",NaN,"0,45%","0,65%","13,53 %"
4,AB - Select US Equity Portfolio W USD Acc,LU1404935386,"USD 49,59","35,80","15,28","-8,02","38,84","6,20","32,08","-0,17","7,10","0,45%","0,65%","13,56 %"

- Estudiemos nulos por columnas.

In [121]:
df.isnull().sum() # sumamos nulos por columnas

Nombre del Fondo               0
ISIN                           0
PRECIO PARTICIPACIÓN           0
rent 2024                      0
rent 2023                      0
rent 2022                      0
rent 2021                     25
rent 2020                     35
rent 2019                     42
rent 2018                     49
rent 2017                     63
Gasto De Gestión Max Anual    13
Gastos Corrientes              0
Volatilidad                    1
dtype: int64

- Como queremos calcular rentabilidades desde 2017, eliminemos filas que no tienen datos en esa fecha y volvamos a estudiar qué pasa.

In [122]:
df = df.dropna(subset=['rent 2017'])
df.head()

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
0,AB - Emerging Markets Low Volatility Equity Po...,LU1005412462,"USD 24,77","17,78","14,54","-17,63","5,33","6,83","18,08","-12,52","16,74","0,85%","1,15%","12,34 %"
2,AB - Select US Equity Portfolio S1 USD Acc,LU0683601610,"USD 85,96","35,60","15,07","-8,20","39,98","5,96","31,68","-0,12","7,37","0,75%","0,82%","13,56 %"
4,AB - Select US Equity Portfolio W USD Acc,LU1404935386,"USD 49,59","35,80","15,28","-8,02","38,84","6,20","32,08","-0,17","7,10","0,45%","0,65%","13,56 %"
5,AB SICAV I - Low Volatility Equity Portfolio I...,LU0861579349,"USD 52,65","24,15","15,31","-5,70","29,23","-2,93","27,98","0,99","5,23","0,70%","0,89%","11,24 %"
13,Allianz Global Investors Fund - Allianz Best S...,LU0788520111,"EUR 2195,29","29,60","21,95","-12,04","35,91","-0,13","27,79","-8,18","8,20","1,20%","0,72%","13,66 %"

- Si observamos bien, hemos eliminado todos los datos de rentabilidad nulos, ya que si tenían nulos en 2018 (por ejemplo) implicaba que también los tuviesen en 2017.

In [123]:
# Cantidad de nulos por columna
df.isnull().sum() # solo quedan 5 en gastos de gestión max anual (columna que no usaremos)

Nombre del Fondo              0
ISIN                          0
PRECIO PARTICIPACIÓN          0
rent 2024                     0
rent 2023                     0
rent 2022                     0
rent 2021                     0
rent 2020                     0
rent 2019                     0
rent 2018                     0
rent 2017                     0
Gasto De Gestión Max Anual    5
Gastos Corrientes             0
Volatilidad                   0
dtype: int64

- Una vez eliminadas las filas innecesarias, reseteamos índices para evitar problemas con filas.

In [124]:
df.reset_index(drop=True, inplace=True)
df.tail() #159 filas resultantes

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
154,Abanca Gestión Conservador FI,ES0133400012,"EUR 10,42","3,91","4,49","-6,18","0,96","0,52","2,86","-2,97","0,64","1,00%","1,44%","3,15 %"
155,Abante Bolsa FI,ES0105011037,"EUR 25,57","18,55","13,56","-15,61","26,50","2,41","24,26","-6,58","7,41","1,25%","1,95%","13,10 %"
156,Abante Global Funds Global Selection Class EUR,LU0861897048,"EUR 14,71","10,08","8,52","-11,00","11,84","0,42","12,08","-5,07","3,02","1,00%","1,89%","7,78 %"
157,Abante Moderado A FI,ES0109655037,"EUR 16,50","8,46","8,05","-9,33","8,84","-2,10","6,84","-6,27","3,23","0,50%","1,12%","6,48 %"
158,Abante Patrimonio Global A FI,ES0105013033,"EUR 21,98","14,16","10,12","-13,36","19,69","-5,37","10,34","-9,81","5,50","1,00%","1,90%","10,55 %"

### 3. Tratamiento de celdas

Ahora vamos a dejar las celdas disponibles para poder operar con ellas.

- Crearemos una función que lo haga directamente.

In [125]:
def limpiador(dato) -> float:
    ''' Elimina caracteres innecesarios y transforma a float '''
    
    # Hago los cambios uno a uno ya que no me deja pasarle un diccionario de cambios
    dato =str(dato)
    sin_coma = dato.replace(',', '.')
    sin_porcentaje = sin_coma.replace('%', '')
    sin_espacios = sin_porcentaje.replace(' ', '')
    return float(sin_espacios)

- Aplicamos la función a las columnas que nos interesan.

In [126]:
df.loc[:, 'rent 2024':'Volatilidad'] = df.loc[:, 'rent 2024':'Volatilidad'].map(limpiador)

# pasamos a formato decimal las columnas de rentabilidad, comisiones y volatilidad
df.loc[:, 'rent 2024':'Volatilidad'] = df.loc[:, 'rent 2024':'Volatilidad']/100
df.head()

,Nombre del Fondo,ISIN,PRECIO PARTICIPACIÓN,rent 2024,rent 2023,rent 2022,rent 2021,rent 2020,rent 2019,rent 2018,rent 2017,Gasto De Gestión Max Anual,Gastos Corrientes,Volatilidad
0,AB - Emerging Markets Low Volatility Equity Po...,LU1005412462,"USD 24,77",0.1778,0.1454,-0.1763,0.0533,0.0683,0.1808,-0.1252,0.1674,0.0085,0.0115,0.1234
1,AB - Select US Equity Portfolio S1 USD Acc,LU0683601610,"USD 85,96",0.356,0.1507,-0.082,0.3998,0.0596,0.3168,-0.0012,0.0737,0.0075,0.0082,0.1356
2,AB - Select US Equity Portfolio W USD Acc,LU1404935386,"USD 49,59",0.358,0.1528,-0.0802,0.3884,0.062,0.3208,-0.0017,0.071,0.0045,0.0065,0.1356
3,AB SICAV I - Low Volatility Equity Portfolio I...,LU0861579349,"USD 52,65",0.2415,0.1531,-0.057,0.2923,-0.0293,0.2798,0.0099,0.0523,0.007,0.0089,0.1124
4,Allianz Global Investors Fund - Allianz Best S...,LU0788520111,"EUR 2195,29",0.296,0.2195,-0.1204,0.3591,-0.0013,0.2779,-0.0818,0.082,0.012,0.0072,0.1366

---
Una vez terminada la limpieza, extraemos el dataframe final.

In [ ]:
df.to_excel('../data/Excel_final_fondos.xlsx')